### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by gzzen** [chris-ckh/dsci-310-group-13#16]
- [ ] A part of helper data is not tractable in the container (-1)
- [ ] A part of helper data is not loaded for test suites, causing tests not runnable (-5)
```
line 116: data2007 = wrangling_data(data2007_test)
Error in wrangling_data(data2007_test) : object 'data2007_test' not found

line 117: data2008 = wrangling_data(data2008_test)
Error in wrangling_data(data2008_test) : object 'data2008_test' not found
```

- [ ] Failed to execute analysis (-5)
```
line 57: colnames(total_list_clean_2007) <- c("Video ID", "uploader", "age", 'category','length','views','rate','ratings','comments','related IDs')
Error in `colnames<-`(`*tmp*`, value = c("Video ID", "uploader", "age",  : 
  attempt to set 'colnames' on an object with less than two dimensions
```
- [ ] Redundant text, i.e., codes that commented out, `TODO` tag (-1)
- [ ] Github milestone is not created for milestone 2 specifically (-2)
- [ ] Project board does not reflect the current state of project, and not associated with issues (-1)
- [ ] Test code should be placed in a separate directory from the functions. You don't want the test code to run every time when you load the functions (-1)
