### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by gzzen** [chris-ckh/dsci-310-group-13#34]
# Milestone 3
- [ ] Please further abstract the analysis code presented in `.rmd` document. The literate code document's sole job is to narrate your analysis, display your analysis artifacts (-3)
- [ ] Please improve the readability of `Makefile` by including comments and documentation (-5)
- [ ] Please improve the functionality of `Makefile` such that the `make clean` command also removes the `output` directory (-1)
- [ ] Please update the *dependencies* section in `README.md` so that it includes the most recent packages, i.e. `testthat` (-2)
- [ ] Please ensure every feature & fix to be operated under a separate branch, and merge into the main branch using pull requests (-1)
- [ ] Please ensure issues contain descriptive information. For example, `modelling stuff` could be too generic. Also please make use of the "assignee" functionality. (-1)
- [ ] Please only include necessary file. i.e. `analysis.ipynb` is not needed but still appears in the repository (-1)
- [ ] Please include more detailed instruction in the procedure of generating the report, for example, where to find the analysis output, assuming that the viewer knows nothing about the project structure (-1)
---
# Addressment of previous feedback
The parts that appeared on previous milestone feedback, and has been addressed adequately is labelled with `addressed`, and 50% marks are given back.
- #2  (+6)
- #16 (+5)
